server.port=8081
spring.application.name=auth-service
spring.config.import=optional:file:../../.env[.properties],optional:file:../.env[.properties],optional:file:.env[.properties]

app.auth.username=${APP_AUTH_USERNAME}
app.auth.password=${APP_AUTH_PASSWORD}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-hours=24

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
