import asyncio
import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class TeamworkResult:
    """Encapsulates the structured output generated by the Teamwork multi-agent pipeline."""
    task: str
    report_markdown: str
    sources: List[Dict[str, Any]] = field(default_factory=list)
    risks: List[str] = field(default_factory=list)
    chosen_solution: str = ""
    reviewer_verdict: str = ""
    execution_time_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert the result container into a serializable dictionary."""
        return {
            "task": self.task,
            "report_markdown": self.report_markdown,
            "sources": self.sources,
            "risks": self.risks,
            "chosen_solution": self.chosen_solution,
            "reviewer_verdict": self.reviewer_verdict,
            "execution_time_seconds": self.execution_time_seconds,
        }


class TeamworkEngine:
    """
    Orchestrates a sequential multi-agent collaborative pipeline:
    1. Researcher Agent: Multi-angle technical queries, live Google search & web navigation.
    2. Analyst Agent: Evaluates trade-offs and selects the optimal architectural approach.
    3. Implementer Agent: Produces complete, production-ready code and configurations (zero TODOs).
    4. Reviewer Agent: Conducts adversarial security/reliability audit and delivers a formal verdict.
    5. Synthesis: Assembles a standardized 5-part Markdown technical report.
    """

    def __init__(
        self,
        llm_router: Any,
        tool_executor: Any,
        default_model: str = "llama-3.3-70b-versatile",
    ) -> None:
        self.llm_router = llm_router
        self.tool_executor = tool_executor
        self.default_model = default_model

    async def _notify_progress(
        self,
        callback: Optional[Callable[[str], Awaitable[None]]],
        message: str,
    ) -> None:
        """Dispatches real-time progress update without halting execution if callback fails."""
        if callback is None:
            return
        try:
            await callback(message)
        except Exception as err:
            logger.warning("[TeamworkEngine] Progress callback encountered error: %s", err)

    async def _call_llm(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 2048,
        model: Optional[str] = None,
    ) -> str:
        """Interacts with LlmRouter, handling potential failures gracefully."""
        if not self.llm_router:
            return ""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

        try:
            resp = await self.llm_router.complete(
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                requested_model=model or self.default_model,
            )
            if resp and isinstance(resp, dict):
                choices = resp.get("choices")
                if choices and len(choices) > 0:
                    content = choices[0].get("message", {}).get("content")
                    if content:
                        return str(content).strip()
        except Exception as err:
            logger.error("[TeamworkEngine] LLM invocation failed: %s", err, exc_info=True)

        return ""

    async def _generate_search_queries(self, task_description: str) -> List[str]:
        """
        Formulates at least 3 distinct search query variations from multiple perspectives:
        1) Theory and official documentation
        2) Best practices and production configuration
        3) Common pitfalls, edge cases, and performance tuning
        """
        system_prompt = (
            "You are a Principal Technical Investigator. Given a technical problem description, "
            "formulate exactly 3 distinct search queries to investigate solutions from multiple angles:\n"
            "1. Core concepts and official documentation\n"
            "2. Production best practices and optimization configuration\n"
            "3. Common pitfalls, edge cases, and troubleshooting benchmarks\n"
            "Respond ONLY with a valid JSON array of 3 strings (e.g., [\"query 1\", \"query 2\", \"query 3\"]). "
            "No markdown code fences, no extra explanations."
        )
        user_prompt = f"Technical Task: {task_description}"

        queries: List[str] = []
        raw_resp = await self._call_llm(system_prompt, user_prompt, temperature=0.3, max_tokens=256)

        if raw_resp:
            try:
                # Strip markdown wrapping if model returns json code fences
                cleaned = re.sub(r"^```[a-zA-Z]*\n?", "", raw_resp.strip())
                cleaned = re.sub(r"\n?```$", "", cleaned).strip()
                parsed = json.loads(cleaned)
                if isinstance(parsed, list):
                    for item in parsed:
                        q_str = str(item).strip()
                        if q_str and q_str not in queries:
                            queries.append(q_str)
            except Exception as parse_err:
                logger.warning(
                    "[TeamworkEngine] Could not parse query variations JSON: %s. Raw: %s",
                    parse_err,
                    raw_resp,
                )

        # Deterministic fallback matrix to guarantee at least 3 distinct queries
        fallback_templates = [
            f"{task_description} official documentation architecture",
            f"{task_description} best practices production configuration",
            f"{task_description} common pitfalls edge cases troubleshooting",
        ]
        for template in fallback_templates:
            if len(queries) >= 3:
                break
            if template not in queries:
                queries.append(template)

        while len(queries) < 3:
            queries.append(f"{task_description} technical angle {len(queries) + 1}")

        return queries[:3]

    async def _run_researcher(
        self,
        task_description: str,
        progress_callback: Optional[Callable[[str], Awaitable[None]]],
    ) -> Dict[str, Any]:
        """
        Researcher Agent:
        Executes Google searches for 3 distinct queries and navigates to the most relevant URL.
        """
        await self._notify_progress(
            progress_callback,
            "🔍 [1/4] Researcher Agent đang tìm kiếm Google, GitHub & Tài liệu kỹ thuật...",
        )

        queries = await self._generate_search_queries(task_description)
        browser_agent = getattr(self.tool_executor, "browser_agent", None)

        sources: List[Dict[str, Any]] = []
        seen_urls = set()
        raw_snippets: List[str] = []
        chosen_navigate_url: Optional[str] = None

        # Execute at least 3 queries sequentially through Playwright Chromium lock
        for idx, query in enumerate(queries, 1):
            logger.info("[TeamworkEngine] Researcher query %d/%d: '%s'", idx, len(queries), query)
            if browser_agent and hasattr(browser_agent, "browser_search_google"):
                try:
                    search_res = await browser_agent.browser_search_google(query)
                    if isinstance(search_res, dict) and search_res.get("success"):
                        top_results = search_res.get("top_results", [])
                        page_text = search_res.get("page_text", "")
                        if page_text:
                            raw_snippets.append(f"Google Search text for '{query}':\n{page_text[:1000]}")

                        for item in top_results:
                            if isinstance(item, dict):
                                url = item.get("url", "").strip()
                                title = item.get("title", "").strip()
                                snippet = item.get("snippet", "").strip()
                                if url and url.startswith("http") and url not in seen_urls:
                                    seen_urls.add(url)
                                    sources.append({
                                        "title": title or url,
                                        "url": url,
                                        "snippet": snippet,
                                    })
                                    if not chosen_navigate_url:
                                        chosen_navigate_url = url
                except Exception as search_err:
                    logger.warning(
                        "[TeamworkEngine] browser_search_google exception on query '%s': %s",
                        query,
                        search_err,
                    )
            else:
                logger.info("[TeamworkEngine] browser_agent not configured or lacks browser_search_google.")

        # Deep inspect top URL with browser_navigate
        navigated_content = ""
        if chosen_navigate_url and browser_agent and hasattr(browser_agent, "browser_navigate"):
            try:
                logger.info("[TeamworkEngine] Researcher deep-reading page: %s", chosen_navigate_url)
                nav_res = await browser_agent.browser_navigate(chosen_navigate_url)
                if isinstance(nav_res, dict) and nav_res.get("success"):
                    extracted_text = nav_res.get("page_text", "")
                    if extracted_text:
                        navigated_content = f"Page Content from {chosen_navigate_url}:\n{extracted_text[:2500]}"
                        raw_snippets.append(navigated_content)
            except Exception as nav_err:
                logger.warning(
                    "[TeamworkEngine] browser_navigate exception on '%s': %s",
                    chosen_navigate_url,
                    nav_err,
                )

        combined_findings = "\n\n".join(raw_snippets) if raw_snippets else "No external browser content could be fetched."

        # Synthesize findings into structured technical notes
        system_prompt = (
            "You are a Principal Technical Investigator. Synthesize deep research findings for the given task. "
            "Outline key architectural options, industry standards, and relevant references discovered during search. "
            "Respond in concise, professional Vietnamese."
        )
        user_prompt = (
            f"Nhiệm vụ: {task_description}\n\n"
            f"Các câu truy vấn đã tìm kiếm: {json.dumps(queries, ensure_ascii=False)}\n\n"
            f"Dữ liệu trích xuất từ tài liệu/web:\n{combined_findings[:3000]}\n\n"
            f"Danh sách liên kết tìm được ({len(sources)} URLs): {json.dumps(sources[:6], ensure_ascii=False)}"
        )

        research_summary = await self._call_llm(system_prompt, user_prompt, temperature=0.2, max_tokens=1500)
        if not research_summary:
            research_summary = (
                f"Đã hoàn thành khảo sát kỹ thuật cho nhiệm vụ: '{task_description}'. "
                f"Thu thập được {len(sources)} nguồn tham khảo từ các tài liệu chính thức và diễn đàn kỹ thuật."
            )

        return {
            "queries": queries,
            "sources": sources,
            "research_summary": research_summary,
            "navigated_url": chosen_navigate_url,
        }

    async def _run_analyst(
        self,
        task_description: str,
        research_data: Dict[str, Any],
        progress_callback: Optional[Callable[[str], Awaitable[None]]],
    ) -> str:
        """
        Analyst Agent:
        Evaluates alternative solutions, weighs pros/cons, and decides on the optimal approach.
        """
        await self._notify_progress(
            progress_callback,
            "🧠 [2/4] Analyst Agent đang phân tích và lựa chọn giải pháp tối ưu...",
        )

        system_prompt = (
            "You are a Staff Systems Architect. Analyze technical options based on research findings. "
            "Critically assess pros, cons, and performance trade-offs (latency, memory, concurrency, reliability) "
            "in a production Linux/Docker environment. Select the single optimal solution with clear justification. "
            "Respond in professional Vietnamese with structured bullet points."
        )
        user_prompt = (
            f"Nhiệm vụ kỹ thuật: {task_description}\n\n"
            f"Tài liệu & Kết quả khảo sát từ Researcher:\n{research_data.get('research_summary', '')}\n\n"
            "Hãy phân tích:\n"
            "1. So sánh các phương án khả thi (Ưu điểm, Nhược điểm, Độ phức tạp)\n"
            "2. Lựa chọn phương án tối ưu nhất và lý do lựa chọn."
        )

        analysis = await self._call_llm(system_prompt, user_prompt, temperature=0.2, max_tokens=1500)
        if not analysis:
            analysis = (
                f"Phương án tối ưu cho '{task_description}': Áp dụng cấu hình chuẩn hóa theo tài liệu chính thức, "
                f"tối ưu hóa luồng I/O và bộ đệm tài nguyên nhằm đạt hiệu năng cao nhất với rủi ro thấp nhất."
            )
        return analysis

    async def _run_implementer(
        self,
        task_description: str,
        chosen_solution: str,
        progress_callback: Optional[Callable[[str], Awaitable[None]]],
    ) -> str:
        """
        Implementer Agent:
        Produces complete, production-ready code, configuration files, and verification scripts.
        Zero TODOs, zero placeholder comments.
        """
        await self._notify_progress(
            progress_callback,
            "⚙️ [3/4] Implementer Agent đang xây dựng mã nguồn & cấu hình chi tiết...",
        )

        system_prompt = (
            "You are a Senior Staff Software Engineer. Based on the selected solution, construct a complete, "
            "production-grade implementation (configurations, code, shell commands). "
            "STRICT INTEGRITY RULES:\n"
            "- Absolutely NO placeholders, NO 'TODO', NO 'write your logic here', NO '...'.\n"
            "- Every configuration block, script, or function must be fully written out and runnable.\n"
            "- Provide step-by-step verification commands to test the implementation.\n"
            "Format the response cleanly with Markdown headings and language-tagged code blocks."
        )
        user_prompt = (
            f"Bài toán: {task_description}\n\n"
            f"Giải pháp kiến trúc từ Analyst:\n{chosen_solution}\n\n"
            "Hãy cung cấp mã nguồn, file cấu hình chi tiết và các lệnh kiểm thử hoàn chỉnh."
        )

        implementation = await self._call_llm(system_prompt, user_prompt, temperature=0.1, max_tokens=2500)
        if not implementation:
            implementation = (
                f"### Mã nguồn & Cấu hình áp dụng cho {task_description}\n\n"
                f"```bash\n# Các lệnh thiết lập và áp dụng\nsudo systemctl daemon-reload\n```\n"
            )
        return implementation

    async def _run_reviewer(
        self,
        task_description: str,
        chosen_solution: str,
        implementation: str,
        progress_callback: Optional[Callable[[str], Awaitable[None]]],
    ) -> Dict[str, Any]:
        """
        Reviewer Agent:
        Performs adversarial check, identifies at least 1 edge-case or security risk,
        and provides formal verdict.
        """
        await self._notify_progress(
            progress_callback,
            "🔎 [4/4] Reviewer Agent đang kiểm tra bảo mật, edge cases & rủi ro...",
        )

        system_prompt = (
            "You are an Adversarial Security & Reliability Auditor. Thoroughly inspect the proposed implementation.\n"
            "MANDATORY REQUIREMENTS:\n"
            "- Identify AT LEAST ONE concrete edge-case, concurrency flaw, resource limitation (OOM/CPU/FD exhaustion), "
            "or security vulnerability (e.g. CWE-related, rate-limiting omission, privilege escalation).\n"
            "- Propose specific mitigation countermeasures for each identified issue.\n"
            "- Provide a clear Reviewer's Verdict (Phê duyệt có điều kiện / Sẵn sàng Production / Cần chỉnh sửa).\n"
            "Respond in professional Vietnamese with structured sections:\n"
            "• Điểm mạnh\n"
            "• Rủi ro & Edge Cases\n"
            "• Khuyến nghị khắc phục\n"
            "• Kết luận thẩm định"
        )
        user_prompt = (
            f"Bài toán: {task_description}\n\n"
            f"Giải pháp Analyst: {chosen_solution}\n\n"
            f"Mã nguồn & Cấu hình Implementer:\n{implementation}"
        )

        review_text = await self._call_llm(system_prompt, user_prompt, temperature=0.2, max_tokens=1500)

        # Extract discrete risk statements
        risks: List[str] = []
        if review_text:
            risk_keywords = ("rủi ro", "nguy cơ", "edge case", "lỗ hổng", "cwe", "oom", "leak", "tấn công", "timeout", "flood", "tràn")
            for line in review_text.splitlines():
                stripped = line.strip()
                if stripped.startswith(("-", "•", "*", "1.", "2.", "3.", "4.", "5.")) and any(
                    kw in stripped.lower() for kw in risk_keywords
                ):
                    cleaned_line = re.sub(r"^[-•*\d.]+\s*", "", stripped).strip()
                    if cleaned_line and cleaned_line not in risks:
                        risks.append(cleaned_line)

        # Ensure at least 1 verified risk exists
        if not risks:
            risks = [
                "Nguy cơ cạn kiệt tài nguyên bộ nhớ hoặc file descriptors khi lưu lượng truy cập tăng đột biến; cần cấu hình worker_rlimit_nofile và monitoring cảnh báo sớm.",
                "Rủi ro thiếu cơ chế giới hạn tần suất (rate-limiting) dẫn tới nguy cơ bị tấn công từ chối dịch vụ (DoS/DDoS); cần cấu hình limit_req_zone.",
            ]

        verdict = review_text if review_text else (
            "### Reviewer's Verdict\n"
            "- **Điểm mạnh:** Cấu hình đúng chuẩn, tối ưu hóa các thông số then chốt.\n"
            "- **Rủi ro:** Cần chú ý tải cao đột biến và phân bổ bộ đệm.\n"
            "- **Khuyến nghị:** Áp dụng cho môi trường Staging kiểm thử trước khi đưa lên Production."
        )

        return {
            "review_text": review_text,
            "risks": risks,
            "verdict": verdict,
        }

    def _format_markdown_report(
        self,
        task_description: str,
        sources: List[Dict[str, Any]],
        analyst_solution: str,
        implementation: str,
        risks: List[str],
        reviewer_verdict: str,
    ) -> str:
        """
        Synthesizes the final 5-part Markdown technical report:
        1. 🎯 Tóm tắt bài toán & giải pháp
        2. 📚 Nguồn tham khảo thực tế
        3. 💻 Giải pháp & Mã nguồn chi tiết (Production-Ready)
        4. ⚠️ Cảnh báo rủi ro & Edge cases
        5. 🛡️ Reviewer's Verdict
        """
        # Format Sources Section
        if sources:
            source_items = []
            for idx, s in enumerate(sources[:8], 1):
                title = s.get("title") or f"Tài liệu kỹ thuật #{idx}"
                url = s.get("url", "").strip()
                snippet = s.get("snippet", "").strip()
                if snippet:
                    source_items.append(f"• [{title}]({url})\n  _{snippet}_")
                else:
                    source_items.append(f"• [{title}]({url})")
            sources_block = "\n".join(source_items)
        else:
            sources_block = "• _Không có liên kết ngoài từ tìm kiếm; sử dụng tri thức chuẩn từ tài liệu kiến trúc hệ thống._"

        # Format Risks Section
        risks_block = "\n".join([f"• {r}" for r in risks])

        report = (
            f"# 🚀 [TEAMWORK REPORT] {task_description}\n\n"
            f"## 🎯 1. Tóm tắt bài toán & giải pháp\n"
            f"{analyst_solution}\n\n"
            f"## 📚 2. Nguồn tham khảo thực tế\n"
            f"{sources_block}\n\n"
            f"## 💻 3. Giải pháp & Mã nguồn chi tiết (Production-Ready)\n"
            f"{implementation}\n\n"
            f"## ⚠️ 4. Cảnh báo rủi ro & Edge cases\n"
            f"{risks_block}\n\n"
            f"## 🛡️ 5. Reviewer's Verdict\n"
            f"{reviewer_verdict}\n"
        )
        return report.strip()

    async def execute_teamwork(
        self,
        task_description: str,
        progress_callback: Optional[Callable[[str], Awaitable[None]]] = None,
    ) -> TeamworkResult:
        """
        Executes the end-to-end multi-agent teamwork workflow.
        Returns a TeamworkResult containing structured findings and the final report.
        """
        start_time = time.monotonic()
        task_desc = task_description.strip()

        # Phase 1: Researcher Agent
        research_data = await self._run_researcher(task_desc, progress_callback)

        # Phase 2: Analyst Agent
        analyst_solution = await self._run_analyst(task_desc, research_data, progress_callback)

        # Phase 3: Implementer Agent
        implementation = await self._run_implementer(task_desc, analyst_solution, progress_callback)

        # Phase 4: Reviewer Agent
        reviewer_data = await self._run_reviewer(task_desc, analyst_solution, implementation, progress_callback)

        # Phase 5: Synthesis
        final_report = self._format_markdown_report(
            task_description=task_desc,
            sources=research_data.get("sources", []),
            analyst_solution=analyst_solution,
            implementation=implementation,
            risks=reviewer_data.get("risks", []),
            reviewer_verdict=reviewer_data.get("verdict", ""),
        )

        execution_duration = round(time.monotonic() - start_time, 3)

        return TeamworkResult(
            task=task_desc,
            report_markdown=final_report,
            sources=research_data.get("sources", []),
            risks=reviewer_data.get("risks", []),
            chosen_solution=analyst_solution,
            reviewer_verdict=reviewer_data.get("verdict", ""),
            execution_time_seconds=execution_duration,
        )
