"""
transfer_qr_generator.py — High-Performance In-Memory QR Code Generator.

Generates QR code representations (PNG bytes and SVG string) directly in RAM.
Guarantees 100% Zero-Disk Leak by utilizing in-memory io.BytesIO buffers
without creating temporary files on the SSD.
"""

from __future__ import annotations

import io
import logging
from typing import Optional

import qrcode
import qrcode.constants
import qrcode.image.svg

logger = logging.getLogger(__name__)

# Standard PNG Magic Signature (RFC 2083)
PNG_MAGIC_HEADER = b"\x89PNG\r\n\x1a\n"


def generate_qr_png_bytes(
    url: str,
    box_size: int = 10,
    border: int = 2,
    fill_color: str = "#0f172a",
    back_color: str = "#ffffff",
) -> bytes:
    """
    Generates a raster PNG QR code directly in memory using qrcode and Pillow.

    Why in-memory buffer:
      Operating strictly within an io.BytesIO buffer guarantees zero SSD disk wear
      and eliminates any risk of orphaned temporary files (Zero-Disk Leak), while
      providing instantaneous response times for high-throughput mobile scans.

    Args:
        url: The target link or URI to encode.
        box_size: Size in pixels of each QR box/pixel module (default 10).
        border: Width of quiet zone border in box units (default 2).
        fill_color: Hex or CSS color string for QR modules (default dark navy #0f172a).
        back_color: Hex or CSS color string for background (default white #ffffff).

    Returns:
        bytes: Raw binary PNG data starting with b"\\x89PNG\\r\\n\\x1a\\n".
    """
    if not url:
        raise ValueError("URL cannot be empty for QR code generation")

    # ERROR_CORRECT_M provides ~15% error recovery, optimal for phone camera scans
    qr = qrcode.QRCode(
        version=None,  # Automatically fit minimum version required for payload length
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=box_size,
        border=border,
    )
    qr.add_data(url)
    qr.make(fit=True)

    img = qr.make_image(fill_color=fill_color, back_color=back_color)

    buffer = io.BytesIO()
    try:
        img.save(buffer, format="PNG")
        png_bytes = buffer.getvalue()
    finally:
        buffer.close()

    if not png_bytes.startswith(PNG_MAGIC_HEADER):
        logger.error("[QRGenerator] Generated bytes do not match PNG magic signature")
        raise RuntimeError("Failed to generate valid PNG byte stream")

    return png_bytes


def generate_qr_svg(url: str, box_size: int = 10, border: int = 2) -> str:
    """
    Generates an independent vector SVG string representation for the given URL.

    Why SVG string:
      Allows crisp, infinite-resolution vector rendering directly inside HTML DOM
      without rasterization overhead or image decoding steps on client browsers.

    Args:
        url: The target link or URI to encode.
        box_size: Scaling factor for SVG coordinate boxes.
        border: Quiet zone border width in box units.

    Returns:
        str: Complete standalone SVG XML string starting with <svg and ending with </svg>.
    """
    if not url:
        raise ValueError("URL cannot be empty for QR code generation")

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=box_size,
        border=border,
        image_factory=qrcode.image.svg.SvgPathImage,
    )
    qr.add_data(url)
    qr.make(fit=True)

    img = qr.make_image()
    buffer = io.BytesIO()
    try:
        img.save(buffer)
        svg_content = buffer.getvalue().decode("utf-8")
    finally:
        buffer.close()

    return svg_content
