server.port=8083
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=5
spring.application.name=file-service
spring.config.import=optional:file:../../.env[.properties],optional:file:../.env[.properties],optional:file:.env[.properties]

ssh.host=${SSH_HOST}
ssh.port=${SSH_PORT}
ssh.user=${SSH_USER}
ssh.password=${SSH_PASSWORD}
ssh.strict-host-key-checking=${SSH_STRICT_HOST_KEY_CHECKING:no}
ssh.fallback-host=${SSH_FALLBACK_HOST:}
ssh.fallback-port=${SSH_FALLBACK_PORT:22}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-hours=24

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
