server.port=8080
spring.application.name=mini-server-dashboard
spring.config.import=optional:file:.env[.properties]

# SSH Configuration from Environment Variables
ssh.host=${SSH_HOST}
ssh.port=${SSH_PORT}
ssh.user=${SSH_USER}
ssh.password=${SSH_PASSWORD}

# Actuator: chỉ expose health endpoint cho healthcheck của Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
